#!/usr/bin/env python3
"""Exact rational/surd audit of the conditional lower-bound ledger."""

from __future__ import annotations

import json
from pathlib import Path

import sympy as sp


Q = sp.Rational
s40 = sp.sqrt(40)
mu = Q(7, 8000)
h0 = Q(1, 10_000_000)
K = Q(4656, 25)
H = Q(39, 10) * K + mu**2 / 2
theta = mu**2 / (16 * H)
near_width = theta * h0 / 20
drift_gap = near_width / 8
C0 = 100 * s40 / h0
Cout = Q(400 * 1_000_000**2, 1883**2)
CN = (4 / mu**2) * (48 + 6 * K + H * C0)
CI = Cout + CN + 4 * s40 / drift_gap
KR = 84 * s40 / (19 * drift_gap)
CF = KR + 3 * (Cout + CN)
recurrence_packet = Q(1872, 5)
terminal_packet = Q(2808, 5)
terminal_exit = Q(18252, 25)
total_packet = recurrence_packet + terminal_packet
A = 6 * total_packet
B = Q(39, 5) * total_packet + terminal_exit
M = Q(78, 5)
Gamma = (20 * M) ** 4
candidates = [
    sp.Integer(1),
    1 / (4 * CI**2),
    1 / (8 * A),
    1 / (64 * B**2 * CF**2),
]
c3 = candidates[3]
HERE = Path(__file__).resolve().parent


def main() -> None:
    assert sp.simplify(4 * H * theta - mu**2 / 4) == 0
    assert sp.simplify(near_width - 8 * drift_gap) == 0
    assert A == 5616
    assert B == Q(200772, 25)
    assert Gamma == 9_475_854_336
    assert all(bool(sp.ask(sp.Q.positive(value))) for value in candidates)

    # The fourth candidate is the minimum.  SymPy proves each exact
    # difference positive in the real quadratic field generated by sqrt(10).
    for other in candidates[:3]:
        difference = sp.radsimp(other - c3)
        assert bool(sp.ask(sp.Q.positive(difference)))

    printed = sp.N(c3, 80)
    # Sprint 1238 advertises only the displayed 16 significant digits.  Its
    # Decimal helper is not treated as an exact source beyond that display.
    expected = sp.Float("4.294654614327144e-52", 80)
    relative = abs((printed - expected) / expected)
    assert relative < sp.Float("1e-15", 80)

    print("==== CONDITIONAL LOWER-BOUND LEDGER AUDIT ====")
    print(f"PASS A = {A}")
    print(f"PASS B = {B}")
    print(f"PASS Gamma = {Gamma}")
    print(f"PASS c = {printed}")
    print("PASS c is the exact minimum of the four registered candidates")
    report = {
        "status": "exact arithmetic audit of conditional dimension-necessity ledger",
        "A": str(A),
        "B": str(B),
        "Gamma": str(Gamma),
        "c_decimal_80": str(printed),
        "candidate_four_is_exact_minimum": True,
        "universal_lower_bound_proved": False,
        "blocker": "near-fixed localized-response/commutator estimate",
        "all_gates_pass": True,
    }
    (HERE / "post-blind-exact-audit.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
